apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorex-app-fe
  labels:
    app: lorexweb1
spec:
  replicas: 1  #fix pods overwrite
  selector:
    matchLabels:
      app: lorexweb1
  template:
    metadata:
      labels:
        app: lorexweb1
    spec:
      containers:
      - name: lorex-app-fe
        image: lorexhub/lorexweb1:__REPLACE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lorex-app-fe-service
spec:
  type: NodePort
  selector:
    app: lorexweb1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080