apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorex-app-fe-deployment
  labels:
    app: lorex-app-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lorex-app-fe
  template:
    metadata:
      labels:
        app: lorex-app-fe
    spec:
      containers:
      - name: lorex-app-fe
        image: lorexhub/lorexweb1:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lorex-app-fe-service
spec:
  type: NodePort
  selector:
    app: lorex-app-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080 
