apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorex-app-fe
  namespace: lorexapp
  labels:
    app: lorexweb1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lorexweb1
  template:
    metadata:
      labels:
        app: lorexweb1
    spec:
      containers:
        - name: lorexweb1-container
          image: lorexhub/lorexweb1:latest  # Will be overridden by Jenkins
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lorex-app-fe-service
  namespace: lorexapp
spec:
  selector:
    app: lorexweb1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
